name: Build Stylus Export

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ["docs/**"]
  push:
    branches: [main]
    paths-ignore: ["docs/**"]

jobs:
  build:
    if: github.repository == 'catppuccin/userstyles'
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.USERSTYLES_TOKEN }}

      - name: Setup Deno
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v2.1.3

      - name: Generate Stylus import
        run: deno task stylus-import

      - name: Upload release artifact
        run: gh release upload --clobber all-userstyles-export ./dist/import.json
        env:
          GH_TOKEN: ${{ github.token }}
