name: Generate Health Files

on:
  workflow_dispatch:
  push:
    paths:
      - "src/generate/**/*"

env:
  DENO_DIR: deno_cache

jobs:
  generate-health-files:
    runs-on: ubuntu-latest
    name: Re-generate README, CODEOWNERS, pr-labeler.yml & issue-labeler.yml
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('src/generate/deno.lock') }}
          path: ${{ env.DENO_DIR }}

      - name: Update README, CODEOWNERS, pr-labeler.yml & issue-labeler.yml
        working-directory: src/generate
        run: ./generate.ts

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: README, CODEOWNERS & labeler.yml"
          branch: ${{ github.ref }}
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
