name: Lint Userstyles

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ["docs/**"]
  push:
    branches: [main]
    paths-ignore: ["docs/**"]

permissions: {}

jobs:
  lint:
    if: github.repository == 'catppuccin/userstyles'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Deno
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v2.1.3

      - name: Lint
        run: deno task lint
