name: Sync Maintainers

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["scripts/userstyles.yml"]

jobs:
  sync-maintainers:
    if: github.repository == 'catppuccin/userstyles'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Deno
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v2.3.5

      - name: Sync maintainers
        run: deno task ci:sync-maintainers
        env:
          GITHUB_TOKEN: ${{ secrets.USERSTYLES_TOKEN }}
