name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["scripts/userstyles.yml"]

permissions: {}

jobs:
  deploy:
    if: github.repository == 'catppuccin/userstyles'
    runs-on: ubuntu-latest

    environment: website
    steps:
      - name: Deploy via cURL
        shell: bash
        env:
          DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: curl -X POST "$DEPLOY_HOOK"
